name: CI/CD to AWS

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]
on:
  workflow_dispatch:

jobs:

  backend-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: cd backend && docker build --build-arg MONGO_DB_USER=${{ secrets.MONGO_DB_USER }} --build-arg MONGO_DB_PASS=${{ secrets.MONGO_DB_PASS }} --build-arg AWS_S3_ID=${{ secrets.AWS_S3_ID }} --build-arg AWS_S3_SECRET=${{ secrets.AWS_S3_SECRET }} --build-arg AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }} . --file Dockerfile --tag esaintor/express-app:latest
    - name: Push the Docker image
      run: docker push esaintor/express-app:latest
      
  backend-aws:
    needs: backend-build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to AWS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BACKEND_INSTANCE }}
        username: ubuntu
        key: ${{ secrets.API_KEY }}
        port: 22
        script: |
          sudo docker pull esaintor/express-app
          sudo docker-compose up -d

  frontend-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: cd frontend && docker build . --file Dockerfile --tag esaintor/express-web:latest
    - name: Push the Docker image
      run: docker push esaintor/express-web:latest

  frontend-aws:
    needs: frontend-build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to AWS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FRONTEND_INSTANCE }}
        username: ubuntu
        key: ${{ secrets.WEB_KEY }}
        port: 22
        script: |
          sudo docker pull esaintor/express-web
          sudo docker-compose up -d
